[build]
  command = "npm run build:netlify"
  publish = "out"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Referrer-Policy = "strict"
